"use Client";

import { useContext } from "react";
import { AppContext } from "@/context/AppContextProvider";

// custom hooks help prevent typescript warnings generated by setting createContext<AppContextType | null>(null)
// by showing that an error will be thrown if the context doesn't exist. The if block that throws the error is VERY important
// to get typescript to stop screaming...

export function useAppContext() {
  const appContext = useContext(AppContext);

  if (!appContext) {
    throw new Error("useAppContext has to be used within <AppContextProvider>");
  }

  return { ...appContext };
}
